[package]
name = "tamatoa"
version = "0.1.0"
edition = "2021"
authors = ["Logan Mzz"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
